<Project>
  <!-- 引入其他 props 文件 -->
  <Import Project="Directory.Build.Other.props" />
  <Import Project="Directory.Build.Volo.props" />

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Authors>lulifa(卢立法)</Authors>
    <Company>RuichenShuxin</Company>
    <Version>9.3.5</Version>
    <Copyright>Copyright © 2025 lulifa(卢立法)</Copyright>
    <Description>RuichenShuxin.AbpPro 是一个基于 ABP 框架构建的现代化后台管理系统，开箱即用，支持快速开发与二次扩展。</Description>


    <RepositoryUrl>https://github.com/lulifa/lulifa-ruichenshuxin-abppro.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/lulifa/lulifa-ruichenshuxin-abppro.git</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>package-readme.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>


    <NoWarn>$(NoWarn);CS1591;CS0436;CS8618;NU1803</NoWarn>
    <Nullable>disable</Nullable>
    <AbpProjectType>app</AbpProjectType>

    <!-- Define versions for referenced packages -->
    <VoloAbpPackageVersion>9.3.5</VoloAbpPackageVersion>
    <MicrosoftPackageVersion>9.0.10</MicrosoftPackageVersion>
    <AspNetCorePackageVersion>9.0.0</AspNetCorePackageVersion>
    <AspNetSecurityOAuthPackageVersion>9.4.1</AspNetSecurityOAuthPackageVersion>
    <DotNetCoreCAPPackageVersion>8.4.1</DotNetCoreCAPPackageVersion>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.8.0" PrivateAssets="All">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ConfigureAwait.Fody" Version="3.3.2" PrivateAssets="All"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)icon.png" Pack="true" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)package-readme.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="**\*.abppkg" />
    <None Remove="**\*.abppkg.analyze.json" />
    <Content Remove="$(UserProfile)\.nuget\packages\*\*\contentFiles\any\*\*.abppkg*" />
  </ItemGroup>

</Project>

