<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>RuichenShuxin.AbpPro</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Authorization" />
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\frameworks\data-protection\RuichenShuxin.AbpPro.DataProtection.Abstractions\RuichenShuxin.AbpPro.DataProtection.Abstractions.csproj" />
    <ProjectReference Include="..\RuichenShuxin.AbpPro.Domain.Shared\RuichenShuxin.AbpPro.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
