<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>RuichenShuxin.AbpPro.Storage</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Authorization" />
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RuichenShuxin.AbpPro.Storage.Domain.Shared\RuichenShuxin.AbpPro.Storage.Domain.Shared.csproj" />
  </ItemGroup>

</Project>