<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>RuichenShuxin.AbpPro</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AutoMapper" />
    <PackageReference Include="Volo.Abp.Ddd.Domain" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\frameworks\authorization\RuichenShuxin.AbpPro.Authorization.OrganizationUnits\RuichenShuxin.AbpPro.Authorization.OrganizationUnits.csproj" />
    <ProjectReference Include="..\..\modules\data-protection\RuichenShuxin.AbpPro.DataProtectionManagement.Domain\RuichenShuxin.AbpPro.DataProtectionManagement.Domain.csproj" />
    <ProjectReference Include="..\..\modules\platform\RuichenShuxin.AbpPro.Platform.Domain\RuichenShuxin.AbpPro.Platform.Domain.csproj" />
    <ProjectReference Include="..\RuichenShuxin.AbpPro.Domain.Shared\RuichenShuxin.AbpPro.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
