<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>RuichenShuxin.AbpPro.Core</AssemblyName>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    
    <PackageReference Include="DistributedLock.Redis" />
    <PackageReference Include="Volo.Abp" />
    <PackageReference Include="Volo.Abp.AspNetCore" />
    <PackageReference Include="Volo.Abp.Autofac" />
    <PackageReference Include="Volo.Abp.Core" />
    <PackageReference Include="Volo.Abp.Swashbuckle" />
    <PackageReference Include="Volo.Abp.AspNetCore.MultiTenancy" />
    <PackageReference Include="Volo.Abp.Caching.StackExchangeRedis" />
    <PackageReference Include="Volo.Abp.DistributedLocking" />
    <PackageReference Include="Volo.Abp.Account.Web.OpenIddict" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" />

  </ItemGroup>

</Project>
