<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>RuichenShuxin.AbpPro.DataProtection.EntityFrameworkCore</AssemblyName>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RuichenShuxin.AbpPro.DataProtection\RuichenShuxin.AbpPro.DataProtection.csproj" />
  </ItemGroup>

</Project>
