<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>RuichenShuxin.AbpPro.AspNetCore.Mvc.Wrapper</AssemblyName>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RuichenShuxin.AbpPro.AspNetCore.Wrapper\RuichenShuxin.AbpPro.AspNetCore.Wrapper.csproj" />
    <ProjectReference Include="..\RuichenShuxin.AbpPro.Wrapper\RuichenShuxin.AbpPro.Wrapper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="RuichenShuxin\AbpPro\AspNetCore\Mvc\Wrapper\Localization\Resources\*.json" />
  </ItemGroup>

</Project>
