<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>RuichenShuxin.AbpPro.DataProtection.Abstractions</AssemblyName>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.ObjectExtending" />
    <PackageReference Include="Volo.Abp.Localization" />
    <PackageReference Include="Volo.Abp.MultiTenancy" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="RuichenShuxin\AbpPro\DataProtection\Localization\Resources\*.json" />
  </ItemGroup>

</Project>
