// Global using directives

global using AutoMapper;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using RuichenShuxin.AbpPro.Core;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Dynamic.Core;
global using System.Linq.Expressions;
global using System.Threading.Tasks;
global using Volo.Abp;
global using Volo.Abp.Account;
global using Volo.Abp.Application;
global using Volo.Abp.Application.Dtos;
global using Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations;
global using Volo.Abp.AspNetCore.Mvc.MultiTenancy;
global using Volo.Abp.AutoMapper;
global using Volo.Abp.Data;
global using Volo.Abp.EventBus.Distributed;
global using Volo.Abp.FeatureManagement;
global using Volo.Abp.Identity;
global using Volo.Abp.Modularity;
global using Volo.Abp.MultiTenancy;
global using Volo.Abp.ObjectExtending;
global using Volo.Abp.PermissionManagement;
global using Volo.Abp.SettingManagement;
global using Volo.Abp.Specifications;
global using Volo.Abp.TenantManagement;
global using Volo.Abp.Users;
global using IdentityRole = Volo.Abp.Identity.IdentityRole;
global using IdentityUser = Volo.Abp.Identity.IdentityUser;
