<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>RuichenShuxin.AbpPro.Platform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AutoMapper" />
    <PackageReference Include="Volo.Abp.Ddd.Application" />
    <PackageReference Include="Volo.Abp.Account.Application" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" />
    <PackageReference Include="Volo.Abp.Identity.Application" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RuichenShuxin.AbpPro.Platform.Application.Contracts\RuichenShuxin.AbpPro.Platform.Application.Contracts.csproj" />
    <ProjectReference Include="..\RuichenShuxin.AbpPro.Platform.Domain\RuichenShuxin.AbpPro.Platform.Domain.csproj" />
  </ItemGroup>

</Project>
