<Project Sdk="Microsoft.NET.Sdk.Web">
  
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>RuichenShuxin.AbpPro</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'RuichenShuxin.AbpPro.HttpApi.Host' " />

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Volo.Abp.AspNetCore.MultiTenancy" />
    <PackageReference Include="Volo.Abp.AspNetCore.Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\frameworks\authorization\RuichenShuxin.AbpPro.Authorization.OrganizationUnits\RuichenShuxin.AbpPro.Authorization.OrganizationUnits.csproj" />
    <ProjectReference Include="..\..\frameworks\cap\RuichenShuxin.AbpPro.CAP\RuichenShuxin.AbpPro.CAP.csproj" />
    <ProjectReference Include="..\..\frameworks\oauth\RuichenShuxin.AbpPro.OAuth\RuichenShuxin.AbpPro.OAuth.csproj" />
    <ProjectReference Include="..\..\frameworks\wrapper\RuichenShuxin.AbpPro.AspNetCore.Mvc.Wrapper\RuichenShuxin.AbpPro.AspNetCore.Mvc.Wrapper.csproj" />
    
    
    <ProjectReference Include="..\..\modules\data-protection\RuichenShuxin.AbpPro.DataProtectionManagement.HttpApi\RuichenShuxin.AbpPro.DataProtectionManagement.HttpApi.csproj" />
    <ProjectReference Include="..\..\modules\data-protection\RuichenShuxin.AbpPro.DataProtectionManagement.Application\RuichenShuxin.AbpPro.DataProtectionManagement.Application.csproj" />
    
    
    <ProjectReference Include="..\..\modules\platform\RuichenShuxin.AbpPro.Platform.HttpApi\RuichenShuxin.AbpPro.Platform.HttpApi.csproj" />
    <ProjectReference Include="..\..\modules\platform\RuichenShuxin.AbpPro.Platform.Application\RuichenShuxin.AbpPro.Platform.Application.csproj" />
    
    
    <ProjectReference Include="..\RuichenShuxin.AbpPro.Application\RuichenShuxin.AbpPro.Application.csproj" />
    <ProjectReference Include="..\RuichenShuxin.AbpPro.EntityFrameworkCore\RuichenShuxin.AbpPro.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\RuichenShuxin.AbpPro.HttpApi\RuichenShuxin.AbpPro.HttpApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

</Project>
