namespace RuichenShuxin.AbpPro.DataProtectionManagement;

public abstract class DataProtectionManagementApplicationServiceBase : AbpProAppServiceBase<DataProtectionResource, DataProtectionManagementApplicationModule>
{
}
