// Global using directives

global using AutoMapper;
global using JetBrains.Annotations;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Options;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using OpenIddict.Abstractions;
global using RuichenShuxin.AbpPro.Authorization.OrganizationUnits;
global using RuichenShuxin.AbpPro.Core;
global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using System.Globalization;
global using System.Linq;
global using System.Text.Json.Nodes;
global using System.Threading;
global using System.Threading.Tasks;
global using Volo.Abp;
global using Volo.Abp.AuditLogging;
global using Volo.Abp.Authorization.Permissions;
global using Volo.Abp.AutoMapper;
global using Volo.Abp.BackgroundJobs;
global using Volo.Abp.Caching;
global using Volo.Abp.Data;
global using Volo.Abp.DependencyInjection;
global using Volo.Abp.Domain;
global using Volo.Abp.Domain.Entities.Auditing;
global using Volo.Abp.Domain.Entities.Events.Distributed;
global using Volo.Abp.Domain.Repositories;
global using Volo.Abp.Domain.Services;
global using Volo.Abp.EventBus;
global using Volo.Abp.EventBus.Distributed;
global using Volo.Abp.FeatureManagement;
global using Volo.Abp.Guids;
global using Volo.Abp.Identity;
global using Volo.Abp.Linq;
global using Volo.Abp.Modularity;
global using Volo.Abp.MultiTenancy;
global using Volo.Abp.OpenIddict;
global using Volo.Abp.OpenIddict.Applications;
global using Volo.Abp.OpenIddict.Scopes;
global using Volo.Abp.PermissionManagement;
global using Volo.Abp.PermissionManagement.Identity;
global using Volo.Abp.PermissionManagement.OpenIddict;
global using Volo.Abp.SettingManagement;
global using Volo.Abp.Settings;
global using Volo.Abp.Specifications;
global using Volo.Abp.TenantManagement;
global using Volo.Abp.Uow;
global using IdentityRole = Volo.Abp.Identity.IdentityRole;
global using IdentityUser = Volo.Abp.Identity.IdentityUser;
global using UserManager = Volo.Abp.Identity.IdentityUserManager;
